server:
  port: 9001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kafka_example
    username: root
    password: Mo.9063069090
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

app:
  kafka:
    url: localhost:9092
